name: Simple Echo Workflow

on: [push] # This workflow runs on every push to the repository

jobs:
  build:
    runs-on: ubuntu-latest # The job will run on the latest Ubuntu runner

    steps:
      - name: Checkout repository # Step to get the code from the repository
        uses: actions/checkout@v4

      - name: Greet the world # Step to print a greeting
        run: echo "Hello, GitHub Actions!"
